# Generated by Django 3.1.5 on 2021-05-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210506_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.EmailField(default='hello@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='Password',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
