# Generated by Django 3.2.2 on 2021-06-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210601_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Mobile_No',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
