# Generated by Django 3.2.2 on 2021-06-03 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
