# Generated by Django 3.2.2 on 2021-06-03 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 3, 13, 51, 23, 496592)),
        ),
    ]
